name: AudioGen Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd extensions/labgraph_audiogen 
        python -m pip install --upgrade pip
        pip install https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-linux_x86_64.whl\#sha256\=a7a49d459bf4862f64f7bc1a68beccf8881c2fa9f3e0569608e16ba6f85ebf7b
        pip install https://download.pytorch.org/whl/cu118/torchaudio-2.0.2%2Bcu118-cp310-cp310-linux_x86_64.whl\#sha256\=26692645ea061a005c57ec581a2d0425210ac6ba9f923edf11cc9b0ef3a111e9
        pip install -e .
        pip install pytest

    - name: Run tests
      run: |
        cd extensions/labgraph_audiogen
        pytest